log_level: info

behavior:
  read_only: false
  dolt_transaction_commit: true

listener:
  host: localhost
  port: 5432
  read_timeout_millis: 28800000
  write_timeout_millis: 28800000
  allow_cleartext_passwords: true

data_dir: data/testing_how_commit_works

cfg_dir: .doltcfg/testing_how_commit_works
privilege_file: .doltcfg/testing_how_commit_works/privileges.db
auth_file: .doltcfg/testing_how_commit_works/auth.db
branch_control_file: .doltcfg/testing_how_commit_works/branch_control.db

metrics:
  labels: {}
  host: localhost
  port: 11228
